server:
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:h2/data.sql
      mode: always

my-env:
  jwt:
    key: f22c10e473c9e953a4648b8e7d6f0a0f5d1c6c7df171be8f7469cde7549d5e99

logging:
  level:
    com.com.example.websocket: DEBUG
    org.hibernate.type: TRACE